In [9]:
import pandas as pd

Cogemos algunos de los datos que parecen más interesantes desde la API de OpenSky, haciendo una llamada de prueba

Nota: Hace falta instalar el paquete de opensky_api: pip install "git+https://github.com/openskynetwork/opensky-api.git#subdirectory=python"

In [ ]:
from opensky_api import OpenSkyApi, TokenManager

#SOlo hace falta registrarse para tener x10 más tokens para llamadas (no es estrictamente necesario); borrar lo de token_manager si no quereis
api = OpenSkyApi(token_manager=TokenManager.from_json_file("credentials.json"))

In [13]:
states = api.get_states()
departures = api.get_departures_by_airport("EDDF", begin=1517227200, end=1517230800)
arrivals = api.get_arrivals_by_airport("EDDF", begin=1517227200, end=1517230800)
flights = api.get_flights_from_interval(begin=1517227200, end=1517230800)

Paso los objetos a dataframe de Pandas para más fácil manipulación

In [14]:
states_df = pd.DataFrame([flight.__dict__ for flight in states.states])
departures_df = pd.DataFrame([flight.__dict__ for flight in departures])
arrivals_df = pd.DataFrame([flight.__dict__ for flight in arrivals])
flights_df = pd.DataFrame([flight.__dict__ for flight in flights])

In [ ]:
display(states_df.head())
display(departures_df.head())
display(arrivals_df.head())
display(flights_df.head())

,icao24,callsign,origin_country,time_position,last_contact,longitude,latitude,baro_altitude,on_ground,velocity,true_track,vertical_rate,sensors,geo_altitude,squawk,spi,position_source,category
0,39de4e,TVF8337,France,1.776933e+09,1776932873,8.7600,41.4504,11574.78,False,193.75,341.42,0.00,None,11742.42,None,False,0,0
1,3ffc22,DMVRG,Germany,1.776933e+09,1776932873,10.8812,49.7908,807.72,False,54.94,226.14,-0.33,None,982.98,None,False,0,0
2,801638,AXB1256,India,1.776933e+09,1776932873,87.7878,25.1210,8534.40,False,201.53,7.92,0.00,None,8953.50,1474,False,0,0
3,39de4d,TVF57JF,France,1.776933e+09,1776932874,4.4896,41.0139,9517.38,False,213.92,10.39,7.80,None,9784.08,None,False,0,0
4,39de4c,TVF57JG,France,1.776933e+09,1776932874,8.5668,44.1931,11269.98,False,243.39,135.94,-0.33,None,11399.52,7622,False,0,0

,icao24,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign,estDepartureAirportHorizDistance,estDepartureAirportVertDistance,estArrivalAirportHorizDistance,estArrivalAirportVertDistance,departureAirportCandidatesCount,arrivalAirportCandidatesCount
0,3c4ad0,1517230790,EDDF,1517238306,None,DLH630,4319,65,NaN,NaN,1,0
1,3c5469,1517230716,EDDF,1517233481,LSGG,DLH5LA,4362,103,1803.0,163.0,1,2
2,4baa03,1517230625,EDDF,1517238702,None,THY9AD,3764,80,NaN,NaN,2,0
3,4951d0,1517230550,EDDF,1517240237,LPCS,TAP583,3808,80,14016.0,708.0,2,3
4,780b7d,1517230493,EDDF,1517295442,None,CES220,1464,11,NaN,NaN,1,0

,icao24,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign,estDepartureAirportHorizDistance,estDepartureAirportVertDistance,estArrivalAirportHorizDistance,estArrivalAirportVertDistance,departureAirportCandidatesCount,arrivalAirportCandidatesCount
0,0101be,1517220729,None,1517230737,EDDF,MSR785,NaN,NaN,1593,95,0,2
1,3c6675,1517227831,EDDT,1517230709,EDDF,DLH187,191.0,54.0,3000,103,1,3
2,3c6663,1517226907,None,1517230498,EDDF,DLH8JT,NaN,NaN,3307,126,0,3
3,3c64c3,1517196397,None,1517230408,EDDF,DLH543,NaN,NaN,4478,126,0,3
4,501d7d,1517222295,None,1517230331,EDDF,ADR114,NaN,NaN,357,95,0,2

,icao24,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign,estDepartureAirportHorizDistance,estDepartureAirportVertDistance,estArrivalAirportHorizDistance,estArrivalAirportVertDistance,departureAirportCandidatesCount,arrivalAirportCandidatesCount
0,e48bb0,1517227957,SBSP,1517229087,None,ONE6004,5036.0,493.0,NaN,NaN,1,0
1,05a02e,1517227761,VRMM,1517228622,None,8QMBD,1604.0,74.0,NaN,NaN,0,0
2,491146,1517229250,LPPT,1517229984,None,TAP1102,4966.0,716.0,NaN,NaN,2,0
3,49d3f9,1517228777,LKPR,1517229614,LKHV,OKHHH,1148.0,113.0,5730.0,186.0,0,2
4,a31e36,1517228758,KHPN,1517230090,KOQU,N30NS,519.0,11.0,24871.0,1076.0,0,1

In [16]:
states.time

1776932874

Ahora cogemos datos del precio del combustible de los aviones. He encontrado dos opciones gratuitas:
- Usar datos de 2020-2026 semanales por región de un dataset de Kaggle (el Excel está en Github): https://www.kaggle.com/datasets/belbino/global-fuel-prices-20202026?resource=download
- Usar Yahoo finance para tener datos en streaming (incluso por minuto) pero solo de EEUU o Europa

In [17]:
import yfinance as yf

#brent = yf.download("BZ=F", period="1mo", interval="1h")
#wti = yf.download("CL=F", period="1mo", interval="1h")
brent = yf.download("BZ=F", period="1d", interval="1m")

[*********************100%***********************]  1 of 1 completed

In [18]:
brent

Price,Close,High,Low,Open,Volume
Ticker,BZ=F,BZ=F,BZ=F,BZ=F,BZ=F
Datetime,,,,,
2026-04-23 04:00:00+00:00,103.339996,103.419998,103.339996,103.419998,0
2026-04-23 04:01:00+00:00,103.300003,103.300003,103.300003,103.300003,2
2026-04-23 04:02:00+00:00,103.300003,103.300003,103.279999,103.300003,12
2026-04-23 04:03:00+00:00,103.199997,103.230003,103.199997,103.230003,18
2026-04-23 04:06:00+00:00,103.389999,103.389999,103.349998,103.349998,10
...,...,...,...,...,...
2026-04-23 08:12:00+00:00,97.629997,97.669998,97.580002,97.660004,13
2026-04-23 08:13:00+00:00,97.459999,97.690002,97.459999,97.669998,38
2026-04-23 08:14:00+00:00,97.550003,97.550003,97.550003,97.550003,1
2026-04-23 08:15:00+00:00,97.489998,97.620003,97.489998,97.620003,17
2026-04-23 08:16:00+00:00,97.349998,97.459999,97.349998,97.459999,0

In [26]:
df_fuel = pd.read_csv("global_fuel_prices_2020_2026.csv", sep=";", header=1)

In [27]:
df_fuel.head()

,date,country,region,income_level,subsidy_level,petrol_usd_liter,diesel_usd_liter,lpg_usd_liter,brent_crude_usd,tax_percentage
0,2020-01-06,United States,North America,High,Low,1.465,1.289,1.093,65.75,59.6
1,2020-01-13,United States,North America,High,Low,1.435,1.319,1.077,65.54,27.6
2,2020-01-20,United States,North America,High,Low,1.446,1.329,1.080,66.51,62.3
3,2020-01-27,United States,North America,High,Low,1.488,1.359,1.125,68.79,44.8
4,2020-02-03,United States,North America,High,Low,1.457,1.341,1.111,68.44,51.4

In [35]:
df_fuel.groupby('region').first().reset_index()

,region,date,country,income_level,subsidy_level,petrol_usd_liter,diesel_usd_liter,lpg_usd_liter,brent_crude_usd,tax_percentage
0,Africa,2020-01-06,Egypt,Low,Very High,0.070,0.082,0.061,65.75,28.1
1,Asia,2020-01-06,China,Middle,Medium,0.980,0.973,0.722,65.75,4.1
2,Europe,2020-01-06,United Kingdom,High,Low,2.542,2.385,1.931,65.75,61.2
3,Middle East,2020-01-06,Saudi Arabia,High,Very High,0.182,0.092,0.129,65.75,17.9
4,North America,2020-01-06,United States,High,Low,1.465,1.289,1.093,65.75,59.6
5,Oceania,2020-01-06,Australia,High,Low,2.102,2.017,1.588,65.75,15.2
6,South America,2020-01-06,Brazil,Middle,Medium,1.264,1.166,0.960,65.75,8.6

In [29]:
countries = df_fuel['country'].unique()
display(countries)
print(len(countries))

array(['United States', 'Canada', 'Mexico', 'Brazil', 'Argentina',
       'Colombia', 'Chile', 'Peru', 'Venezuela', 'Ecuador',
       'United Kingdom', 'Germany', 'France', 'Italy', 'Spain',
       'Netherlands', 'Belgium', 'Sweden', 'Norway', 'Denmark', 'Finland',
       'Poland', 'Portugal', 'Greece', 'Switzerland', 'Austria',
       'Ireland', 'Hungary', 'Czech Republic', 'Romania', 'Russia',
       'Ukraine', 'Turkey', 'China', 'Japan', 'South Korea', 'India',
       'Indonesia', 'Malaysia', 'Thailand', 'Vietnam', 'Philippines',
       'Bangladesh', 'Pakistan', 'Sri Lanka', 'Nepal', 'Myanmar',
       'Singapore', 'Hong Kong', 'Taiwan', 'Australia', 'New Zealand',
       'Saudi Arabia', 'UAE', 'Kuwait', 'Qatar', 'Iran', 'Iraq', 'Israel',
       'Jordan', 'Lebanon', 'Egypt', 'South Africa', 'Nigeria', 'Kenya',
       'Ethiopia', 'Ghana', 'Tanzania', 'Morocco', 'Algeria', 'Libya',
       'Tunisia', 'Angola', 'Mozambique', 'Zambia', 'Zimbabwe', 'Uganda',
       'Cameroon', 'Senegal', 'Ivory Coast', 'Sudan', 'Botswana',
       'Namibia', 'Rwanda'], dtype=object)

84

Hay solo datos de 84 países de los 195 que hay en el mundo, pero dentro de un mismo continente puede ser similar

In [30]:
df_fuel['region'].unique()

array(['North America', 'South America', 'Europe', 'Asia', 'Oceania',
       'Middle East', 'Africa'], dtype=object)

In [32]:
df_fuel.groupby('region')['brent_crude_usd'].mean()

region
Africa           106.686453
Asia             106.686453
Europe           106.686453
Middle East      106.686453
North America    106.686453
Oceania          106.686453
South America    106.686453
Name: brent_crude_usd, dtype: float64

brent_crude_usd parece que es un precio a nivel global

In [36]:
df_fuel.groupby('region')['petrol_usd_liter'].mean()

region
Africa           1.549482
Asia             2.140571
Europe           3.701695
Middle East      1.225935
North America    2.064176
Oceania          3.655203
South America    1.425393
Name: petrol_usd_liter, dtype: float64

Lista de las variables más importantes:

- estDepartureAirport
- estArrivalAirport
- firstSeen / lastSeen
- petrol_usd_liter
- brent_crude_usd
- tax_percentage
- velocity
- baro_altitude / geo_altitude
- region
- on_ground
- departure/arrival candidates count
- origin_country